### ISSUE TITLE
Control does not disconnect when switching locomotive operation modes if a destination is set

### ISSUE THREAD

**Issue by celendis** [Erabior/RouteManager#1]
Issue: When changing locomotive mode from road when at least one passenger stop location is selected, the AI driver does not disconnect.

Steps to reproduce:
1. Select Road mode and select at least one destination
2. Select Manual mode
3. Observe that the game UI indicates that Manual mode is active
4. Attempt to adjust locomotive controls, such as applying brakes
5. Observe that the locomotive controls still override the player control. while the UI mode indicates otherwise

Expected Result: When selecting manual mode, the AI should immediately change to manual operation, regardless of destination selection.

Thank you very much for developing this mod. It really is a great improvement in the near term, until such a feature is added to the base game.

**Comment by Erabior** [comment]
Fixed with Version 1.0.1.0
