### ISSUE TITLE
Statitions not unchecking after stops are made

### ISSUE THREAD

**Issue by Cjane142** [Erabior/RouteManager#10]
![image](https://github.com/Erabior/RouteManager/assets/108844505/95ab192a-b77b-4014-8425-dbc669c05d68)

Ran the train with AI fine from Whittier to Bryson. Checked the boxes in order of direction per the instructions. 

Once the train reached Bryson, the engine started reversing back to Ela. I checked the Orders tab and saw that none of the stations the train had stopped at had become unchecked.

**Comment by Erabior** [comment]
Could you please tell me what version of the mod you were using when this happened also if there is any way for you to get a video of this happening that would be fantastic

**Comment by Cjane142** [comment]
1.0.1.3

https://drive.google.com/file/d/1NFjv28ogxTFmoIKoTdero5rMuvhMcOIV/view?usp=sharing

Surely. A video of the issue is attached, This train came from Bryson, skipping Ela because the coach had 60 people for Bryson already on it. Train unloaded, only loaded 10 people then left the station.

**Comment by Erabior** [comment]
Please update to the latest version and give me a console output. The console can be enabled in the game directory (railroader/BepInEx/Config) then copy paste the output when it happens please

**Comment by Cjane142** [comment]
I'm unsure of how to open the config file but I can confirm the beta version 1.0.1.6 did not fix the issue.

**Comment by Cjane142** [comment]
[config.zip](https://github.com/Erabior/RouteManager/files/13763952/config.zip)
Here is the config file? is this what you meant in your previous message?

**Comment by Erabior** [comment]
yes this is the config file. You should be able to open it with a text editor like notepad, notepad++ or if neither of those work, Visual Studio Code will be able to open it.

**Comment by Cjane142** [comment]
[BepInEx config file.txt](https://github.com/Erabior/RouteManager/files/13789699/BepInEx.config.file.txt)
Here is the config file.

**Comment by Erabior** [comment]
i just realized, the stations in the orders tab of the loco never get unchecked. The mod is designed to have a loco run continuously back and forth from end to end of the line. The stations in the locomotive UI will only become unselected if you unselect them
