### ISSUE TITLE
Failed to restart from Ela

### ISSUE THREAD

**Issue by hjp766** [Erabior/RouteManager#11]
[weird ela glitch.txt](https://github.com/Erabior/RouteManager/files/13759726/weird.ela.glitch.txt)

Was letting it do its thing and then all of a sudden with no interference it would not restart from Ela... nothing was clicked or changed. Log attached. Unchecked and rechecked route manager and she started away.

**Comment by Erabior** [comment]
potentially fixed with [Beta 1.0.1.6](https://github.com/Erabior/RouteManager/release/tag/1.0.1.6)

**Comment by Erabior** [comment]
Closing due to no replies after potential fix was implemented. Marking as complete
