### ISSUE TITLE
Route list is reset on game load. 

### ISSUE THREAD

**Issue by dtwilliams10** [Erabior/RouteManager#12]
If there is an active route list when you save and quit, when the save is reloaded the route list is reset. This causes a disruption if the train is half way through the station list and then decides to start over when you rebuild the list and re-enable Route Mode.

**Comment by Erabior** [comment]
based on the behavior you are describing I think you may be on an older version of the mod. Please update to the [latest beta version](https://github.com/Erabior/RouteManager/releases/tag/1.0.1.6). there is as 'enable route mod' button now. when resuming the game. select the stations that your train was heading towards only. then press 'enable route mode' and the logic will find the closest station of the selected stations and resume from there as in this case it is a 'terminus' station. once the train departs, you can select the rest of the stations and the mod will function like normal. I will be looking into saving data somehow. but the latest version of the mod should allow you to resume fairly easily.
