### ISSUE TITLE
Unclicking all of the stations while Enable Route Mode is checked causes game crash

### ISSUE THREAD

**Issue by dtwilliams10** [Erabior/RouteManager#15]
<Currently running Beta 1.0.1.5>

I was attempting to terminate a train at Whittier and unchecked all of the stations before unchecking Enable Route Mode. When I unclicked the last station with Enable Route Mode still checked the game froze and crashed. 

I should have just unclicked Enable Route Mode first, but I wasn't thinking until as I was unchecking the last station.

**Comment by Erabior** [comment]
Fixed with [Beta 1.0.1.8](https://github.com/Erabior/RouteManager/releases/tag/1.0.1.8)
