### ISSUE TITLE
Erronious detection of Water and Coal levels for Diesel Locomotives

### ISSUE THREAD

**Issue by AdamC1228** [Erabior/RouteManager#17]
New logic to monitor coal and water is not distinguishing between diesel and steam locomotives causing diesel locomotives to inadvertently halt movement for low water and coal. 

![image](https://github.com/Erabior/RouteManager/assets/13957003/ec9f009a-1821-4d92-a758-b0afa8ccef6c)

Possible avenues forward:

- Ignore diesel locomotives
- Add support for diesel locomotives
- Add option to enable / disable the checks on a per consist basis

**Comment by AdamC1228** [comment]
See pull request for suggested fix.

**Comment by Erabior** [comment]
Added Logic to detect loco archetype when checking coal/water/fuel levels with [Beta 1.0.1.10](https://gihub.com/Erabior/RouteManager/releases/tag/1.0.1.10)

**Comment by AdamC1228** [comment]
Beta 1.0.1.10 does resolve the issue.
