### ISSUE TITLE
Latest build crashes Railroader

### ISSUE THREAD

**Issue by dtwilliams10** [Erabior/RouteManager#2]
Updated from 1.0.0.3 to 1.0.1.0 and the first time I tried to use the mod after the update it crashed the game. Are there any logs I can provide you to help debug this?

I have a passenger train already loaded. When I switch from Manual to Route and click the Enable Route Mode checkbox it locks up the game and then subsequently crashes. Should the Enable checkbox be checked before the stations, or after?

**Comment by dtwilliams10** [comment]
I am clicking the Enable Route Mode button with no stations selected. As soon as I click it the game freezes and crashes.

**Comment by dtwilliams10** [comment]
As an aside (not sure if it's related, if not I'll log a new bug) Route Manager doesn't seem to handle end of the line very well. It tries to drive forward instead of reversing back to the previous station. Not sure if there is a good way to enable a point to point mode that will keep it running back and forth between a set number of stations.

**Comment by Erabior** [comment]
I have not observed this behavior. If you wouldn't mind getting a video or the issue or describing the steps better to reproduce the issue that would greatly help narrow down any potential issues.
