### ISSUE TITLE
Train going wrong direction

### ISSUE THREAD

**Issue by Voidheartd** [Erabior/RouteManager#23]
I had just loaded the train at Bryson with full passengers to Whittier. I had unchecked Ela and Bryson because I wanted the train to stop at Whittier. The train stopped at Ela anyway, and when I tried to stop the route manager and start it again, it now refuses to go towards Whittier no matter what I try. Even saving and reloading does not stop it from going the wrong way.

**Comment by Voidheartd** [comment]
To add onto this, I manually took the train back to Whittier. I then checked Whittier, Ela, and Bryson, and enabled route manager. The train immediately tried to leave the station without picking up passengers.

**Comment by Erabior** [comment]
You should not need to uncheck stations. Yes, the train will stop at Ela even if it is full of passengers for Whittier, but the train will stop for at most 20 seconds and then continue on its way. As far as the issue where the route logic is sending the train to the same station, you can 'clear' the current destination by unchecking the current destination from the list an re-enabling the route logic. This should soft reset the route logic's 'memory'. Again, the mod was designed to handle passengers for solo players so the solo players dont have to worry about it. It is not 100% efficient in that it will stop at every selected station, but it should get the job done if left alone until the loco needs refueling

**Comment by Voidheartd** [comment]
I realized now that what was happening is that the AI wants to leave the current station and come back. I just wasn't waiting long enough to see the rest of the behavior. It drives away from the station some distance, then goes back to the station and continues as normal. Now that I know that's what it's trying to do it's not a problem.

**Comment by Erabior** [comment]
wonderful
