### ISSUE TITLE
Feature Request - Add notifications/terminal entry for train stopped at station and leaving station.

### ISSUE THREAD

**Issue by Narflar** [Erabior/RouteManager#24]
Just as the title says, if it's possible, have an output to the terminal saying the train has stopped at a station and is leaving a station.  Just a way to keep track of what the passenger trains are up to without always checking the map.

**Comment by AdamC1228** [comment]
I think this should be doable. I will propose a pull request with the enhancement.

**Comment by AdamC1228** [comment]
Should be implemented in my latest pull request. We shall see if it gets merged.

**Comment by Narflar** [comment]
That's awesome, thank you!

**Comment by Erabior** [comment]
this has been implemented Thank you [AdamC1228](https://github.com/AdamC1228)
