### ISSUE TITLE
Forward and reverse disappear after selecting Route mode 

### ISSUE THREAD

**Issue by Ranger7984** [Erabior/RouteManager#27]
after selecting route mode and refresing train menu F and R buttons and speed slider diappear
![Uploading Screenshot (351).png…]()

**Comment by Ranger7984** [comment]
![Screenshot (351)](https://github.com/Erabior/RouteManager/assets/155080589/c607df77-3682-4539-81e8-617ad1216ad4)

**Comment by Erabior** [comment]
this bug should be fixed in [Beta 1.0.1.13](https://github.com/Erabior/RouteManager/releases/tag/1.0.1.13)
