### ISSUE TITLE
Train "arrived" at 2 stations at the same time

### ISSUE THREAD

**Issue by Voidheartd** [Erabior/RouteManager#31]
On 1.0.1.12, I started a train with all 3 locations checked that was fully loaded and at Whittier. The train departed (no log messages) and drove to Ela. When it got to Ela it posted in the log that it arrived at Ela and right after that Bryson and was unloading the passengers for both at Ela.

**Comment by AdamC1228** [comment]
Please provide the player log file (C:\Users\%username%\AppData\LocalLow\Giraffe Lab LLC\Railroader\Player.log) for review.

**Comment by Voidheartd** [comment]
Since I'm also using railloader the log file name is different but I just had this issue occur again. The relevant portion is at 3:39:12
[railloader.log](https://github.com/Erabior/RouteManager/files/13808320/railloader.log)

**Comment by AdamC1228** [comment]
I have published an alpha build of the V2 rewrite. Please test and report back if the new code shows any improvement on this issue.

**Comment by Voidheartd** [comment]
Unable to test currently due to other issues with V2. #67

**Comment by AdamC1228** [comment]
@Voidheartd Issue #67 should be resolved. Please retest with the latest v2 release.

**Comment by Voidheartd** [comment]
I haven't seen it in some time so I think we can consider it fixed and I will reopen if it occurs again.
