### ISSUE TITLE
Suggestion to handle "Scrolling" route menu

### ISSUE THREAD

**Issue by GreenBIM** [Erabior/RouteManager#35]
Problem: The stations list on the route menu does not show full list of stations.
Solutions: Being that it is the railcar the determines if passenger service is needed, have one railcar select the stations the player wants. Then replace the stations menu with a pull down to select the railcar to replicate the route from. Additionally, it will identify that rail car as the one that needs to be in the "spotted" zone of the station. This would solve the scrolling issue, but also give the player greater control as to where the train would stop at stations.

**Comment by Erabior** [comment]
The station menu should only show the stations that you have unlocked from progression. The very same code that determines which stations to display on the passenger cars is what the mod uses to determine which stations to display on the route ai ui. If you have more than 3 stations unlocked, you have to mouse wheel to scroll through the list. Using the passenger car as the 'source' of the route AI control would require a fairly large amount of the code to be re-written and at least a handful of new edge cases would need to be handled. There will be a better UI in the future that will make the whole experience much better and will create a 'foundation' upon which the functionality of the mod can be expanded.

**Comment by Narflar** [comment]
> if you have more than 3 stations unlocked, you have to mouse wheel to scroll through the list. 

This may be dependent on resolution.  I only see one station in the list when selecting.
