### ISSUE TITLE
Mod manager conflict

### ISSUE THREAD

**Issue by benlafaut** [Erabior/RouteManager#40]
Not able to get route manager to work if i have multiscreen loaded with unity mod manager.

**Comment by Erabior** [comment]
Im sorry but this is just the nature of modloader wars. I would say i would port my mod over to UMM but there is talk of a potential (and i want be very clear this is just rumor at this point) official mod loader that MAY be implemented into the game in the future. If this is true, there is no point for me to port the mod over to UMM if it is possible that i (and all other mods) would have to do it again for the official mod loader.

**Comment by benlafaut** [comment]
I completely understand. I guess I will have to decide what mod I want to use more, until then.

**Comment by LunarNightShade** [comment]
Just chiming in to say that I've actually been using this (and ShortFused) and Multiscreen at the same time. I got it to work by using the Assembly installation method for UMM, which then leaves DoorstopProxy free for BepInEx to use. I've been using it that way for a few days now and I have not had any issues with it. The only catch with the Assembly install method is that you have to reinstall it after game updates, which I can tolerate as updates, at least for now, are not that frequent. Hopefully the rumors hold true and we do get an official modloader in the future.

**Comment by benlafaut** [comment]
Thanks for the tip. I will give it a try.

**Comment by GamearooCodes** [comment]
> Assembly installation method for UMM
any clue on how to do this??
