### ISSUE TITLE
Brakes no longer apply on regular road mode trips in certain cases.

### ISSUE THREAD

**Issue by LukasJK** [Erabior/RouteManager#49]
Ran up some cars to the ela bridge contstruction on new save with the mod on road mode. The train reaches end of tracks, stops, whistles but does not apply brakes (as is the case in vanilla game) and then starts rolling backwards. 
Route mode not enabled.

**Comment by Erabior** [comment]
This mod does not change road mode at all. The devs did just put out an update that changed some things about the auto engineer which is what controls the road and yard modes. If route mode is not enabled then this mod does effectively nothing to the AI

**Comment by LukasJK** [comment]
@Erabior I'm afraid it does. Would you like the save file? 
AI applies brakes at the EOL without mod; it does not when the mode is in place.

**Comment by AdamC1228** [comment]
Feel free to send the save file and player.log file.

**Comment by LukasJK** [comment]
Seems to be the case of 'turn on video recording software and the issue disappears'. 
Will see if I can find a way to trigger it again somehow

**Comment by Voidheartd** [comment]
I experience this as well. Pretty sure this is a consequence of the new AI behavior, not anything from the mod. Removed the mod and still occurs. The AI just cannot properly stop while going up a grade. It goes too slowly to the stop point, and doesn't apply the brakes, so it keeps rolling backward and having to start moving forward again, over and over. Going down a grade it handles fine.
