### ISSUE TITLE
How to find the .dll file for the beta branch?

### ISSUE THREAD

**Issue by Peccadilloz** [Erabior/RouteManager#55]
Hi, 

I'm terribly sorry for asking such a mundane question, but I couldn't find a download option for the dll file for the beta release. Surely I must be blind. If someone could point me in the right direction, I would appreciate it very much.

Best Regards.

**Comment by Erabior** [comment]
They will be down a little bit on this page: https://github.com/Erabior/RouteManager/releases

**Comment by AdamC1228** [comment]
> Hi,
> 
> I'm terribly sorry for asking such a mundane question, but I couldn't find a download option for the dll file for the beta release. Surely I must be blind. If someone could point me in the right direction, I would appreciate it very much.
> 
> Best Regards.

Its now available at the page Erabior referenced.
