### ISSUE TITLE
AI mode completely disabled for host 

### ISSUE THREAD

**Issue by BubbyCraft** [Erabior/RouteManager#58]
I was using the mod to run 2 passenger trains and noticed that as the host I was not able to swap the engines between forward/reverse when I take them out of route mode. Others in the session could use AI just fine

**Comment by AdamC1228** [comment]
The mod is not guaranteed to work in multiplayer. That said it is my understanding that all players in the session should have the mod installed to prevent any odd behavior. Can you confirm if all parties had the mod installed or if only some did? And identify if those with the mod had this issue? Lastly, please provide the player.log file for yourself and (if possible) one from a player that had no trouble but also had the mod installed?

**Comment by BubbyCraft** [comment]
[Player-prev.log](https://github.com/Erabior/RouteManager/files/13826123/Player-prev.log)
[Player.log](https://github.com/Erabior/RouteManager/files/13826124/Player.log)

**Comment by BubbyCraft** [comment]
Here are my logs, it was me and 2 others that had it installed and no one else in our 8 person crew tonight. I don't believe I will be able to get a log from someone else unfortunately.

**Comment by AdamC1228** [comment]
It would appear that your player.log files are relatively empty. I presume this is because you are using both bepinex and unity mod manager. According to the log files, we will need to get the railroader.log file from your railroader install folder. Can you please provide that log file?

**Comment by BubbyCraft** [comment]
That was my railroader log file. I have never heard of unity mod manager before. I only have the bepinix thing

**Comment by AdamC1228** [comment]
> That was my railroader log file. I have never heard of unity mod manager before. I only have the bepinix thing

Forgive me, In my exhaustion i misread monomanager as mod manager. It appears that because this is a multiplayer session the log files are not entirely contained in the player.log file.

Again, there is another log file in the railroader installation directory (steam game folder) called railroader.log I will need that log too.

A typical log file looks something like this:
```
Begin MonoManager ReloadAssembly
- Completed reload, in  0.206 seconds
[Message:   BepInEx] BepInEx 5.4.22.0 - Railroader (12/22/2023 10:20:58 PM)
[Info   :   BepInEx] Running under Unity v2021.3.33.15620650
[Info   :   BepInEx] CLR runtime version: 4.0.30319.42000
[Info   :   BepInEx] Supports SRE: True
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.Preloader 5.4.22.0]
[Info   :   BepInEx] 1 patcher plugin loaded
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 1 plugin to load
[Info   :   BepInEx] Loading [Dispatcher 2.0.0.2]
[Message:   BepInEx] Chainloader startup complete
<RI> Initializing input.
New input system (experimental) initialized
Using XInput
<RI> Input initialized.
<RI> Initialized touch support.
UnloadTime: 1.335000 ms
2024-01-03 23:26:30Z - Dispatcher_V2.0.0.2 - DEB: Loaded Settings.
2024-01-03 23:26:30Z - Dispatcher_V2.0.0.2 - TRA: EXITING FUNCTION: ApplyRouteManagerSettings
2024-01-03 23:26:30Z - Dispatcher_V2.0.0.2 - DEB: Applied Settings.
2024-01-03 23:26:30Z - Dispatcher_V2.0.0.2 - INF: Log Level is now: Trace
2024-01-03 23:26:30Z - Dispatcher_V2.0.0.2 - INF: --------------------------------------------------------------------------------------------------
2024-01-03 23:26:30Z - Dispatcher_V2.0.0.2 - INF: Dispatcher Initializing
2024-01-03 23:26:30Z - Dispatcher_V2.0.0.2 - INF: --------------------------------------------------------------------------------------------------
2024-01-03 23:26:30Z - Dispatcher_V2.0.0.2 - INF: --------------------------------------------------------------------------------------------------
2024-01-03 23:26:30Z - Dispatcher_V2.0.0.2 - INF: Dispatcher Ready!
2024-01-03 23:26:30Z - Dispatcher_V2.0.0.2 - INF: --------------------------------------------------------------------------------------------------
targetFrameRate = 60
[23:26:30 INF] Railroader 2023.3.2
Tokenized in 0.004, 276 tokens
Setting up 6 worker threads for Enlighten.
2024-01-03 23:26:36Z - Dispatcher_V2.0.0.2 - TRA: ENTERED FUNCTION: LoadRouteManagerSettings
2024-01-03 23:26:36Z - Dispatcher_V2.0.0.2 - VER: Loading Settings
2024-01-03 23:26:36Z - Dispatcher_V2.0.0.2 - TRA: EXITING FUNCTION: LoadRouteManagerSettings
2024-01-03 23:26:36Z - Dispatcher_V2.0.0.2 - DEB: Loaded Settings.
2024-01-03 23:26:36Z - Dispatcher_V2.0.0.2 - TRA: ENTERED FUNCTION: ApplyRouteManagerSettings
2024-01-03 23:26:36Z - Dispatcher_V2.0.0.2 - VER: Applying Settings
2024-01-03 23:26:36Z - Dispatcher_V2.0.0.2 - TRA: EXITING FUNCTION: ApplyRouteManagerSettings
2024-01-03 23:26:36Z - Dispatcher_V2.0.0.2 - DEB: Applied Settings.
2024-01-03 23:26:36Z - Dispatcher_V2.0.0.2 - INF: Log Level is now: Trace
Placer disabled
[23:26:37 WRN] Nothing below player at (0.00, 0.00, 0.00); waiting.
```

Yours looks something like this:
```Begin MonoManager ReloadAssembly
- Completed reload, in  0.099 seconds
[Message:   BepInEx] BepInEx 5.4.22.0 - Railroader (12/11/2023 12:26:33 PM)
[Info   :   BepInEx] Running under Unity v2021.3.33.15620650
[Info   :   BepInEx] CLR runtime version: 4.0.30319.42000
[Info   :   BepInEx] Supports SRE: True
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.Preloader 5.4.22.0]
[Info   :   BepInEx] 1 patcher plugin loaded
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 1 plugin to load
[Info   :   BepInEx] Loading [Dispatcher 1.0.2.1]
[Message:   BepInEx] Chainloader startup complete
<RI> Initializing input.
New input system (experimental) initialized
Using XInput
<RI> Input initialized.

  ______ _   _ _____     ____  ______   _      ____   _____ 
 |  ____| \ | |  __ \   / __ \|  ____| | |    / __ \ / ____|
 | |__  |  \| | |  | | | |  | | |__    | |   | |  | | |  __ 
 |  __| | . ` | |  | | | |  | |  __|   | |   | |  | | | |_ |
 | |____| |\  | |__| | | |__| | |      | |___| |__| | |__| |
 |______|_| \_|_____/   \____/|_|      |______\____/ \_____|
                                                            

Railloader Injector 1.0.0.0 has been loaded. Further logging will be handled by Railloader+Serilog and will not appear in the Player.log anymore.

Due to Unity's behaviour, it is possible that a few events will appear after this notice, but the majority of the game's log will be in the railloader.log in your game directory.
<RI> Initialized touch support.
UnloadTime: 109.988400 ms
Setting up 16 worker threads for Enlighten.
Shader 'Enviro/Skybox': fallback shader 'None' not found
BoxColliders does not support negative scale or size.```

**Comment by BubbyCraft** [comment]
[railloader.log](https://github.com/Erabior/RouteManager/files/13826553/railloader.log)

**Comment by BubbyCraft** [comment]
THat one?

**Comment by AdamC1228** [comment]
Correct, however that one seems to not be complete either. Until we can determine how to get the full logs for a multiplayer session there isn't much that can be done.

**Comment by Helmi** [comment]
Is there anything we can help with from multiplayer sessions? We are a two-people regular session and I could send logs from both parties easily. Anything we can help with to get this multiplayer synced?

**Comment by AdamC1228** [comment]
My initial thoughts after someone else had the same log behavior was an uninstall and re-install of the game. I propose that you verify the integrity of game files at the very least to see if we can get the logging sorted. Ultimately until we can get usable logs there is little that can be done at this time.

**Comment by AdamC1228** [comment]
@Helmi @BubbyCraft 

Please confirm if the proposed actions of verify integrity of game files and/or re-installation has improved the logging situation.

**Comment by BubbyCraft** [comment]
Hi, no, my logs have always been the same. I have shared them with the devs quite a few times and they have never said anything about them being weird.

**Comment by AdamC1228** [comment]
@BubbyCraft @Helmi 

We will be releasing a new version within the next few days. Once that release is published. I would ask that you reproduce and report back.

**Comment by Helmi** [comment]
We can certainly do that. Also please let us know if we're supposed to install on host only or on all clients. Let me know when you released it.

**Comment by AdamC1228** [comment]
> We can certainly do that. Also please let us know if we're supposed to install on host only or on all clients. Let me know when you released it.

As of right now, I recommend all clients.

**Comment by AdamC1228** [comment]
@Helmi @BubbyCraft 

A new version has been released. Just to reconfirm, you are not using any other mods in addition to this? If so please list. If we still cannot get the logging sorted out then another option would be to try the newly available Unity Mod Manager version to see if if the logging issue is related to some BepInEx weirdness. 

Please supply your latest logs after attempting to reproduce with the new versions.

**Comment by BubbyCraft** [comment]
I am only using the graphics mod with my set up. I will install the new version and let you know how it works tonight

**Comment by BubbyCraft** [comment]
I am only seeing a version dated from 2 weeks ago. Was the update released?

**Comment by armyf35** [comment]
@BubbyCraft Try the "Pre-release" versions https://github.com/Erabior/RouteManager/releases/tag/2.0.0.6_Beta

**Comment by BubbyCraft** [comment]
When installing the most recent build, do you remove the file titled RouteManager.dll in favor of the new RouteManager.BepinEx.dll?

**Comment by AdamC1228** [comment]
Yes, I will update the documentation / release notes accordingly with that point

**Comment by BubbyCraft** [comment]
Perfect. I managed to get it figured out too. About to run the session now and will report back afterwards. I'll be streaming it as well so I will make sure if there are any issues to help include timestamps on the stream for you.

**Comment by BubbyCraft** [comment]
Just reporting back here. I had zero issues and was able to now swap between road, yard, and manual freely as well as turn off route mode without any issues what so ever. Any problems I did come across were because I ordered the AI incorrectly. Thank you for the fix, and I would say that you can close my ticket :) This is an awesome mod and I love it very much! Thank you again for your help!

**Comment by AdamC1228** [comment]
> Just reporting back here. I had zero issues and was able to now swap between road, yard, and manual freely as well as turn off route mode without any issues what so ever. Any problems I did come across were because I ordered the AI incorrectly. Thank you for the fix, and I would say that you can close my ticket :) This is an awesome mod and I love it very much! Thank you again for your help!

Thanks for the update. I will mark this issue as resolved. :)
