### ISSUE TITLE
V2 - wasCurrentStopServed - Fails to handle edge case: Train Full

### ISSUE THREAD

**Issue by armyf35** [Erabior/RouteManager#64]
From Dev
Train will not exit a station if all passenger cars are full, and there are valid (Going to a station the train will serve) passengers to take

It loops on `has not finished loading and unloading at _ Station`. It seems like https://github.com/Erabior/RouteManager/blob/138185b6c9adfbb749ec775ca9e6488c456830fb/v2/core/AutoEngineer.cs#L565 will never trigger, `carsLoaded` will eventually be `false` but `passWaiting` will always be `true`

**Comment by AdamC1228** [comment]
Makes sense upon review. During testing and design that is an edge case that I missed. Simple enough fix. I will address this when I work on alpha 2 this weekend.

**Comment by armyf35** [comment]
Just throwing suggestions out there. I think this would work `if (!carsLoaded && (carsAtCapacity || !passWaiting))`, not sure how to check car capacity vs filled amount.

**Comment by AdamC1228** [comment]
That would probably suffice however I would rather break the check out into another if case for 2 reasons.

- Readability / Debugging
- We probably want to print to the console that the train was full and left people behind.

**Comment by AdamC1228** [comment]
Potential fix implemented and now available on the v2-dev branch. Feel free to retest / verify but you will need to manually compile the code.

**Comment by armyf35** [comment]
Looks like that fixed it.
