### ISSUE TITLE
Resuming after manual control to coal breaks stopping pattern

### ISSUE THREAD

**Issue by hjp766** [Erabior/RouteManager#8]
Whenever I stop to coal and water, normally at Bryson after 4 hrs, on resuming by reselecting route mode, the path finding breaks on departure from Bryson. Have to manually drive through the first signal before it will work out what to do and then it normally skips the first intermediate station.

Should we deselect then reselect all stops?

Trying to get accurate video clips.

**Comment by hjp766** [comment]
https://www.dropbox.com/scl/fi/dz5y225vvgkrd06shnza5/MedalTVScreenRecording20231222161728.mkv?rlkey=n2055gwl8c1ch26k5wleu5rhc&dl=0

It is dumping the current route and pax and resetting despite when it sets off having previous pax etc still on board.

**Comment by Erabior** [comment]
please try this [beta](https://github.com/Erabior/RouteManager/releases/tag/1.0.1.4) build I just uploaded and if you wouldn't mind, in the railroader/BepInEx folder there should be a config file that you can open with either Notepad or any text file editor. Please if you would scroll down to "[Logging.Console]" and change enabled from false to true. save the file, please. the next time this incident occurs pause the game and copy a good chunk of what is in the output, preferably where you enabled the route UI after calling and watering. This should be around the time you see something like "Loco {your loco's name} currently has not called a coroutine - Calling the Coroutine with {your loco's name} as an argument"

**Comment by hjp766** [comment]
[route mod bug.txt](https://github.com/Erabior/RouteManager/files/13759022/route.mod.bug.txt)

Interestingly, as I had a freight coming in on the closest platform road at Bryson it totally ignored the second platform road at Bryson too this time and headed straight for Ela... I think. It hasn't got there yet! Will try again with the normal road open next time through.

**Comment by hjp766** [comment]
[route mod bug p2 depart ELA.txt](https://github.com/Erabior/RouteManager/files/13759040/route.mod.bug.p2.depart.ELA.txt)
SO it did run through to Ela skipping Bryson having coaled there inbound from Hemingway when routed to the middle road in Bryson. Will try routing to the normal platform building road next time.

**Comment by hjp766** [comment]
[bryson fail to stop post refill main platform.txt](https://github.com/Erabior/RouteManager/files/13759242/bryson.fail.to.stop.post.refill.main.platform.txt)
Tried again, arrived from Hemingway, coaled and watered before taking the platform.
Restarted from the coal line, routed to main platform, failed to stop, continued to Ela

**Comment by hjp766** [comment]
This time switched to coaling/servicing at Alarka. Took manual control approaching Alarka to stop long to back down to coal with rake attached. Unloaded in manual. Backed down and coaled manually. Pulled forward manually (not setting passenger cars). Reenabled route and it set off without loading at all. Will try next time letting it auto start the turnaround then take over to coal, problem is you have to stop so long to clear the shed track.

[Alarka depot problem.txt](https://github.com/Erabior/RouteManager/files/13759436/Alarka.depot.problem.txt)

**Comment by Erabior** [comment]
potentially fixed with [Beta 1.0.1.6](https://github.com/Erabior/RouteManager/releases/tag/1.0.1.6)

**Comment by Erabior** [comment]
Closing due to no replies after potential fix was implemented. Marking as complete
