### ISSUE TITLE
V2 - Approach Whistle - 2024.01.0 - Conflict with base game new AI crossing whistle.

### ISSUE THREAD

**Issue by Voidheartd** [Erabior/RouteManager#80]
Now that the AI whistles when approaching roads, this can clash with the route manager whistle for approaching stations. Approaching Ela from Bryson for example. It's not a big deal, just doesn't sound great.

**Comment by AdamC1228** [comment]
It will need some adjustments and such is the nature of things as the Dev's improve the game.

**Comment by AdamC1228** [comment]
I have made efforts to mitigate and improve this in alpha 3.

**Comment by AdamC1228** [comment]
Issue appears mitigated in latest commit.
