### ISSUE TITLE
Alpha 3 release includes old routemanager.ini

### ISSUE THREAD

**Issue by Voidheartd** [Erabior/RouteManager#82]
Alpha 3 zip does not include the updated routemanager.ini with the extra options.

**Comment by AdamC1228** [comment]
Although the config.ini does not contain all configurable settings, the mod will use the default values. Those defaults align with the current V2 behavior up to this point. 

At this time I do not have intentions to update the default ini file with every release. That said, the read-me should probably be updated to include what those defaults are so i will flag that for improvement.
