### ISSUE TITLE
Mod does not work

### ISSUE THREAD

**Issue by Tex5021** [Erabior/RouteManager#85]
1/12/24, mod does not work. Does not install "Plugins" folder into BepInEx folder after game is launched then closed.

**Comment by Erabior** [comment]
Did you install BepInEx correctly? If bepenex is installed correctly the plugins folder will be created when the game is launched for the first time after install.

**Comment by Erabior** [comment]
The mod has no bearing on if the plugins folder is created or not. This is almost certainly an issue of improperly installed BepInEx,
