### ISSUE TITLE
V1 - Duplicate Messages - Mod is running on the same loco multiple times simultaneously?

### ISSUE THREAD

**Issue by tyrope** [Erabior/RouteManager#88]
I started up my save this morning, TFSL 2 was previously in "pax mode", but was now in run mode; so I set it to only go to Whittier (it was roughly at mile marker 58) - As it initially went the wrong way I disabled and re-enabled.
![image](https://github.com/Erabior/RouteManager/assets/516490/0b647fe3-2b21-4812-8744-0c2051970ca4)
When it arrived there it messaged twice; I told it to then also stop at Ela and Bryson, and after unloading it spammed those 5 other messages, then departed empty towards Whittier East; getting stuck against a switch against because of the Connelly train.
When undoing the work it ran past Whittier towards Ela, at which point I decided to set it to manual and write this report.

[Player.log](https://github.com/Erabior/RouteManager/files/13938384/Player.log) & [railloader.log](https://github.com/Erabior/RouteManager/files/13938429/railloader.log)

Installed mods (in case it's relevant):
* ADRFDR
* BepInEx
* Better Whistles
* Graphixperiments
* InterchangeUnchained
* Locomotive Cab Nicknames
* Railloader
* RouteManager
* SaveTheSaves

Edit: I'm 99.9% sure I'm running Stable 1.0.2.1

**Comment by AdamC1228** [comment]
I am unsure what the end result would be with the addition of other mods nor have I used any other mod as of yet with Railroader. 

All I can offer is that ***if it is reproducible***, please remove all mods but Route Manager and retest to confirm. If the behavior goes away when the other mods are out of the picture, then that would mean that there is some incompatibility with one of those mods.

**Comment by tyrope** [comment]
Been playing v2 lately and couldn't reproduce.

**Comment by AdamC1228** [comment]
Closing as V2 resolved.
