### ISSUE TITLE
Road mode controls not being re-drawn after route mode disabled

### ISSUE THREAD

**Issue by dtwilliams10** [Erabior/RouteManager#9]
So the scrolling pick list on the Road menu is difficult to make selections from. Since the engine is backfilling the passenger cars with the station list for passengers, could we do the inverse and pick the stations from the passenger cars to drive the AI?

**Comment by Erabior** [comment]
after selecting Route mode, ctrl-click the loco again and the UI will refresh with more room for the route mode controls. I will likely make a new UI panel in the future to fix this issue.

**Comment by Ranger7984** [comment]
after selecting route mode the forward and reverse buttons disappear on the train even after i deselect and refresh train menu it also doesnt show in the yard mode

**Comment by Ranger7984** [comment]
![Screenshot (351)](https://github.com/Erabior/RouteManager/assets/155080589/26933e51-fae6-48bf-b7d3-44c132f1ea9d)

**Comment by Erabior** [comment]
The fix for this was implemented a while ago but I forgot to mention it here. should be fixed update to [Beta 1.0.1.13](https://github.com/Erabior/RouteManager/releases/tag/1.0.1.13) please
